name: CI
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Generate Contributors Images
      uses: jaywcjlove/github-action-contributors@main
      with:
        filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
        avatarSize: 42

    - name: Build Linux Command
      run: |        
        npm install
        npm run dash
        cp CONTRIBUTORS.svg .deploy
        rm -rf .deploy/linux-command.docset

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.3.6
      with:
        package-path: ./package.json

    - name: Update Dash Feed
      run: |
        echo "<entry><version>${{steps.create_tag.outputs.versionNumber}}</version><url>https://jaywcjlove.github.io/linux-command/linux-command.docset.tgz</url></entry>" > .deploy/linux-command-docset.xml

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        commit_message: '[${{steps.tag_version.outputs.tag}}] ${{ github.event.head_commit.message }}'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./.deploy
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com