name: CI Test
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - run: npm install
    - run: npm run build
    - run: node build/dash.js

    - name: Compress linux-command.docset.
      run: zip -r -y linux-command.docset.zip . -x "node_modules/*"
      working-directory: .deploy/linux-command.docset
    - run: cp -rp .deploy/linux-command.docset/linux-command.docset.zip ./

    - run: rm -rf .deploy/linux-command.docset

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.3.6
      with:
        package-path: ./package.json

      # 更新dash feed
    - name: Update Dash Feed
      run: |
        pwd && ls
        echo "<entry><version>${{steps.create_tag.outputs.versionNumber}}</version><url>https://github.com/jaywcjlove/linux-command/releases/download/${{ steps.changelog.outputs.tag }}/linux-command.docset.zip</url></entry>" > linux-command-docset.xml
        git add linux-command-docset.xml
        git commit -m "更新Dash Feed"

      #推送更新至github
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
