name: CI Test
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.3.6
      with:
        package-path: ./package.json

      # 更新dash feed
    - name: Update Dash Feed
      run: |
        echo "<entry><version>${{steps.create_tag.outputs.versionNumber}}</version><url>https://jaywcjlove.github.io/linux-command/linux-command.docset.zip</url></entry>" > linux-command-docset.xml
        git config --global user.email "gclmit@163.com"
        git config --global user.name "gclm"
        git add linux-command-docset.xml
        git commit -m "更新Dash Feed"

      #推送更新至github
    - name: Push Dash Feed
      uses: ad-m/github-push-action@master
