name: CI Test
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - run: npm install
    - run: npm run build
    - run: node build/dash.js

    - name: Compress linux-command.docset.
      run: zip -r -y linux-command.docset.zip . -x "node_modules/*"
      working-directory: .deploy/linux-command.docset
    - run: cp -rp .deploy/linux-command.docset/linux-command.docset.zip ./

    - run: rm -rf .deploy/linux-command.docset

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.3.6
      with:
        package-path: ./package.json

    - name: Update Dash Feed
      run: |
        echo "<entry><version>${{steps.create_tag.outputs.versionNumber}}</version><url>https://jaywcjlove.github.io/linux-command/linux-command.docset.zip</url></entry>" > .deploy/linux-command-docset.xml

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        commit_message: '[${{steps.tag_version.outputs.tag}}] ${{ github.event.head_commit.message }}'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./.deploy
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com

